<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>1.1.0</VersionPrefix>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Authors>Boshi Lian</Authors>
    <Company />
    <Product />
    <Description>A leveldb implementation in C#</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/tg123/IronLeveldb</PackageProjectUrl>
    <RepositoryUrl>https://github.com/tg123/IronLeveldb</RepositoryUrl>
    <PackageTags>leveldb azure blob</PackageTags>
    <RootNamespace>IronLeveldb</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Crc32.NET" Version="1.2.0" />
    <PackageReference Include="Google.Protobuf" Version="3.27.0" />
    <PackageReference Include="Snappy.Sharp" Version="1.0.0" />
  </ItemGroup>

</Project>
